trigger:
  branches:
    include:
      - main

# CHANGE: Use Microsoft's Ubuntu cloud server instead of 'Default'
pool:
  vmImage: 'ubuntu-latest' 

variables:
  imageName: 'poojadocker404/python-demo'
  tag: '$(Build.BuildId)'

stages:

# STAGE 1: Testing
- stage: BuildAndTest
  displayName: "Install and Run Tests"
  jobs:
  - job: Test
    steps:
    # Use the official Python task (This works on Ubuntu cloud!)
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.12'
      displayName: 'Install Python 3.12'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
      displayName: "Install dependencies"

    - script: |
        pytest test_app.py
      displayName: "Run unit tests"

# STAGE 2: Docker Build and Push
- stage: BuildAndPush
  displayName: "Build and Push Docker Image"
  dependsOn: BuildAndTest
  condition: succeeded() # Only run if tests pass
  jobs:
  - job: DockerBuild
    steps:
    - task: Docker@2
      displayName: "Build and Push Image to Docker Hub"
      inputs:
        containerRegistry: 'docker-hub-connection' 
        repository: 'poojadocker404/python-demo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest