trigger:
  branches:
    include:
      - main

# Use your laptop's agent pool
pool:
  name: 'Default' 

variables:
  imageName: 'poojadocker404/python-demo'
  tag: '$(Build.BuildId)'

stages:

# STAGE 1: Testing
- stage: BuildAndTest
  displayName: "Install and Run Tests"
  jobs:
  - job: Test
    steps:
    - script: |
        python --version
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m pip install pytest
      displayName: "Install dependencies"

    - script: |
        python -m pytest test_app.py
      displayName: "Run unit tests"

# STAGE 2: Docker Build and Push
- stage: BuildAndPush
  displayName: "Build and Push Docker Image"
  dependsOn: BuildAndTest
  jobs:
  - job: DockerBuild
    steps:
    - task: Docker@2
      displayName: "Build and Push Image to Docker Hub"
      inputs:
        containerRegistry: 'docker-hub-connection' # Must match your Service Connection name
        repository: 'poojadocker404/python-demo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest