apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-demo
  template:
    metadata:
      labels:
        app: python-demo
    spec:
      serviceAccountName: python-demo-sa
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: jfrog-registry-secret
      containers:
        - name: python-demo
          image: image: 130.131.164.192:8082/art-docker-local/python-demo:16
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
              ephemeral-storage: "100Mi"
            limits:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "200Mi"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: app-storage
              mountPath: /app/data
      volumes:
        - name: app-storage
          emptyDir: {}  # Or use `persistentVolumeClaim` if needed
